### ISSUE TITLE
java.lang.ClassNotFoundException: ch.qos.logback.access.common.spi.ServerAdapter during start

### ISSUE THREAD

**Issue by aschepp** [tomcat-slf4j-logback/tomcat-slf4j-logback-config#39]
The assembly.xml is probably missing the ch.qos.logback.access:common library, because it's not included in the zip file.

```
<dependencySets>
  <dependencySet>
      <unpack>false</unpack>
      <scope>runtime</scope>
      <outputDirectory>lib</outputDirectory>
      <includes>
          <!-- Keep legacy access until tomcat 9 retired -->
          <include>ch.qos.logback:logback-access</include>
          <include>ch.qos.logback:logback-core</include>
          <include>ch.qos.logback.access:tomcat</include>
          <include>ch.qos.logback.access:common</include>
      </includes>
  </dependencySet>
</dependencySets>
```

**Comment by hazendaz** [comment]
@aschepp Thank you, I've transferred this over to the config repo where it needs patched.  If you have time, could you raise a PR to fix same?  I can get to release this later tonight.  If unable to get PR, I can do it then.  Thanks for reporting this.

**Comment by hazendaz** [comment]
> And `<encoder class="ch.qos.logback.access.PatternLayoutEncoder">` needs to be changed to `<encoder class="ch.qos.logback.access.common.PatternLayoutEncoder">` in the logback-access example.

This might take a little more thought as to where to show that / put it.  Have to look to see how that is all setup.  This config is running tomcat 8.5, 9, 10, and 11.

**Comment by aschepp** [comment]
Also, in case you don't know yet. It looks like the

**Comment by hazendaz** [comment]
@aschepp Thanks for all the info, was not aware of that being at issue either.  I'd not yet go to fully working with tomcat 10 and probably a week or two away from hitting all these same problems.  I'll look into this issue more, if I need to I can roll back to the old and re-cut releases there while waiting on final solution.

**Comment by hazendaz** [comment]
ok so logback access is only here for convenience.  This project is about tomcat-juli at its core.  The rest is just to help others out.  So I'm adding comments to the encoder.  I don't know what logstash will or will not do.  I doubt they take that larger PR in full since that drops support for older tomcats.  I think the root of the issues with this really need to be brought up with logback repos since IMO its a mixed bag right now.

That said, @aschepp, if you use the right versions with logback access config as you have noted, does it work?  I realize logstash will not but the main setup with this repo?  At best all I see I can do here is document logback access 1 vs 2.  I could ship both but not seeing a good reason to do so given logback considered the changes to logback minor and it doesn't document if logback access works with both (stages its continued jakarta line only).

**Comment by hazendaz** [comment]
Items address so far.

- The config project now contains the common.jar and released with tomcat 11 module.
- This https://github.com/tomcat-slf4j-logback/tomcat-slf4j-logback-config/pull/42 will bring in info in the config on what to use.

Rest pending more discussion.

**Comment by aschepp** [comment]
I've created a setup by now that works, but it involves some edits. I think I had to touch every library in this logging stack.
